name: Deploy to Delnyx server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H delnyx.fr >> ~/.ssh/known_hosts
        shell: bash

      - name: Pull and deploy latest code
        run: |
          ssh -i ~/.ssh/id_ed25519 delnyx@delnyx.fr << 'EOF'
            cd ~/docker/delnyx/app
            git reset --hard
            git clean -fd
            git pull origin main

            cd ..
            docker compose exec -T app composer install --no-interaction --prefer-dist --optimize-autoloader
            docker compose exec -T app php bin/console cache:clear
            docker compose exec -T app php bin/console doctrine:migrations:migrate --no-interaction
          EOF
        shell: bash
